/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const profileProfileLazyImport = createFileRoute('/(profile)/profile')()
const profileNotificationsLazyImport = createFileRoute(
  '/(profile)/notifications',
)()
const authRegisterLazyImport = createFileRoute('/(auth)/register')()
const authLoginLazyImport = createFileRoute('/(auth)/login')()
const appTransactionsLazyImport = createFileRoute('/(app)/transactions')()
const appStatsLazyImport = createFileRoute('/(app)/stats')()
const appSearchLazyImport = createFileRoute('/(app)/search')()
const appOverviewLazyImport = createFileRoute('/(app)/overview')()
const appNewsLazyImport = createFileRoute('/(app)/news')()
const appMoreLazyImport = createFileRoute('/(app)/more')()
const appMarketsLazyImport = createFileRoute('/(app)/markets')()
const appDetailsLazyImport = createFileRoute('/(app)/details')()
const appAssetsLazyImport = createFileRoute('/(app)/assets')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const profileProfileLazyRoute = profileProfileLazyImport
  .update({
    id: '/(profile)/profile',
    path: '/profile',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(profile)/profile.lazy').then((d) => d.Route))

const profileNotificationsLazyRoute = profileNotificationsLazyImport
  .update({
    id: '/(profile)/notifications',
    path: '/notifications',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(profile)/notifications.lazy').then((d) => d.Route),
  )

const authRegisterLazyRoute = authRegisterLazyImport
  .update({
    id: '/(auth)/register',
    path: '/register',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/register.lazy').then((d) => d.Route))

const authLoginLazyRoute = authLoginLazyImport
  .update({
    id: '/(auth)/login',
    path: '/login',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/login.lazy').then((d) => d.Route))

const appTransactionsLazyRoute = appTransactionsLazyImport
  .update({
    id: '/(app)/transactions',
    path: '/transactions',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(app)/transactions.lazy').then((d) => d.Route))

const appStatsLazyRoute = appStatsLazyImport
  .update({
    id: '/(app)/stats',
    path: '/stats',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(app)/stats.lazy').then((d) => d.Route))

const appSearchLazyRoute = appSearchLazyImport
  .update({
    id: '/(app)/search',
    path: '/search',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(app)/search.lazy').then((d) => d.Route))

const appOverviewLazyRoute = appOverviewLazyImport
  .update({
    id: '/(app)/overview',
    path: '/overview',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(app)/overview.lazy').then((d) => d.Route))

const appNewsLazyRoute = appNewsLazyImport
  .update({
    id: '/(app)/news',
    path: '/news',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(app)/news.lazy').then((d) => d.Route))

const appMoreLazyRoute = appMoreLazyImport
  .update({
    id: '/(app)/more',
    path: '/more',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(app)/more.lazy').then((d) => d.Route))

const appMarketsLazyRoute = appMarketsLazyImport
  .update({
    id: '/(app)/markets',
    path: '/markets',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(app)/markets.lazy').then((d) => d.Route))

const appDetailsLazyRoute = appDetailsLazyImport
  .update({
    id: '/(app)/details',
    path: '/details',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(app)/details.lazy').then((d) => d.Route))

const appAssetsLazyRoute = appAssetsLazyImport
  .update({
    id: '/(app)/assets',
    path: '/assets',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(app)/assets.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(app)/assets': {
      id: '/(app)/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof appAssetsLazyImport
      parentRoute: typeof rootRoute
    }
    '/(app)/details': {
      id: '/(app)/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof appDetailsLazyImport
      parentRoute: typeof rootRoute
    }
    '/(app)/markets': {
      id: '/(app)/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof appMarketsLazyImport
      parentRoute: typeof rootRoute
    }
    '/(app)/more': {
      id: '/(app)/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof appMoreLazyImport
      parentRoute: typeof rootRoute
    }
    '/(app)/news': {
      id: '/(app)/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof appNewsLazyImport
      parentRoute: typeof rootRoute
    }
    '/(app)/overview': {
      id: '/(app)/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof appOverviewLazyImport
      parentRoute: typeof rootRoute
    }
    '/(app)/search': {
      id: '/(app)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof appSearchLazyImport
      parentRoute: typeof rootRoute
    }
    '/(app)/stats': {
      id: '/(app)/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof appStatsLazyImport
      parentRoute: typeof rootRoute
    }
    '/(app)/transactions': {
      id: '/(app)/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof appTransactionsLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/(profile)/notifications': {
      id: '/(profile)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof profileNotificationsLazyImport
      parentRoute: typeof rootRoute
    }
    '/(profile)/profile': {
      id: '/(profile)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof profileProfileLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof appAssetsLazyRoute
  '/details': typeof appDetailsLazyRoute
  '/markets': typeof appMarketsLazyRoute
  '/more': typeof appMoreLazyRoute
  '/news': typeof appNewsLazyRoute
  '/overview': typeof appOverviewLazyRoute
  '/search': typeof appSearchLazyRoute
  '/stats': typeof appStatsLazyRoute
  '/transactions': typeof appTransactionsLazyRoute
  '/login': typeof authLoginLazyRoute
  '/register': typeof authRegisterLazyRoute
  '/notifications': typeof profileNotificationsLazyRoute
  '/profile': typeof profileProfileLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof appAssetsLazyRoute
  '/details': typeof appDetailsLazyRoute
  '/markets': typeof appMarketsLazyRoute
  '/more': typeof appMoreLazyRoute
  '/news': typeof appNewsLazyRoute
  '/overview': typeof appOverviewLazyRoute
  '/search': typeof appSearchLazyRoute
  '/stats': typeof appStatsLazyRoute
  '/transactions': typeof appTransactionsLazyRoute
  '/login': typeof authLoginLazyRoute
  '/register': typeof authRegisterLazyRoute
  '/notifications': typeof profileNotificationsLazyRoute
  '/profile': typeof profileProfileLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(app)/assets': typeof appAssetsLazyRoute
  '/(app)/details': typeof appDetailsLazyRoute
  '/(app)/markets': typeof appMarketsLazyRoute
  '/(app)/more': typeof appMoreLazyRoute
  '/(app)/news': typeof appNewsLazyRoute
  '/(app)/overview': typeof appOverviewLazyRoute
  '/(app)/search': typeof appSearchLazyRoute
  '/(app)/stats': typeof appStatsLazyRoute
  '/(app)/transactions': typeof appTransactionsLazyRoute
  '/(auth)/login': typeof authLoginLazyRoute
  '/(auth)/register': typeof authRegisterLazyRoute
  '/(profile)/notifications': typeof profileNotificationsLazyRoute
  '/(profile)/profile': typeof profileProfileLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/details'
    | '/markets'
    | '/more'
    | '/news'
    | '/overview'
    | '/search'
    | '/stats'
    | '/transactions'
    | '/login'
    | '/register'
    | '/notifications'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/details'
    | '/markets'
    | '/more'
    | '/news'
    | '/overview'
    | '/search'
    | '/stats'
    | '/transactions'
    | '/login'
    | '/register'
    | '/notifications'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/(app)/assets'
    | '/(app)/details'
    | '/(app)/markets'
    | '/(app)/more'
    | '/(app)/news'
    | '/(app)/overview'
    | '/(app)/search'
    | '/(app)/stats'
    | '/(app)/transactions'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(profile)/notifications'
    | '/(profile)/profile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appAssetsLazyRoute: typeof appAssetsLazyRoute
  appDetailsLazyRoute: typeof appDetailsLazyRoute
  appMarketsLazyRoute: typeof appMarketsLazyRoute
  appMoreLazyRoute: typeof appMoreLazyRoute
  appNewsLazyRoute: typeof appNewsLazyRoute
  appOverviewLazyRoute: typeof appOverviewLazyRoute
  appSearchLazyRoute: typeof appSearchLazyRoute
  appStatsLazyRoute: typeof appStatsLazyRoute
  appTransactionsLazyRoute: typeof appTransactionsLazyRoute
  authLoginLazyRoute: typeof authLoginLazyRoute
  authRegisterLazyRoute: typeof authRegisterLazyRoute
  profileNotificationsLazyRoute: typeof profileNotificationsLazyRoute
  profileProfileLazyRoute: typeof profileProfileLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appAssetsLazyRoute: appAssetsLazyRoute,
  appDetailsLazyRoute: appDetailsLazyRoute,
  appMarketsLazyRoute: appMarketsLazyRoute,
  appMoreLazyRoute: appMoreLazyRoute,
  appNewsLazyRoute: appNewsLazyRoute,
  appOverviewLazyRoute: appOverviewLazyRoute,
  appSearchLazyRoute: appSearchLazyRoute,
  appStatsLazyRoute: appStatsLazyRoute,
  appTransactionsLazyRoute: appTransactionsLazyRoute,
  authLoginLazyRoute: authLoginLazyRoute,
  authRegisterLazyRoute: authRegisterLazyRoute,
  profileNotificationsLazyRoute: profileNotificationsLazyRoute,
  profileProfileLazyRoute: profileProfileLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(app)/assets",
        "/(app)/details",
        "/(app)/markets",
        "/(app)/more",
        "/(app)/news",
        "/(app)/overview",
        "/(app)/search",
        "/(app)/stats",
        "/(app)/transactions",
        "/(auth)/login",
        "/(auth)/register",
        "/(profile)/notifications",
        "/(profile)/profile"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(app)/assets": {
      "filePath": "(app)/assets.lazy.tsx"
    },
    "/(app)/details": {
      "filePath": "(app)/details.lazy.tsx"
    },
    "/(app)/markets": {
      "filePath": "(app)/markets.lazy.tsx"
    },
    "/(app)/more": {
      "filePath": "(app)/more.lazy.tsx"
    },
    "/(app)/news": {
      "filePath": "(app)/news.lazy.tsx"
    },
    "/(app)/overview": {
      "filePath": "(app)/overview.lazy.tsx"
    },
    "/(app)/search": {
      "filePath": "(app)/search.lazy.tsx"
    },
    "/(app)/stats": {
      "filePath": "(app)/stats.lazy.tsx"
    },
    "/(app)/transactions": {
      "filePath": "(app)/transactions.lazy.tsx"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.lazy.tsx"
    },
    "/(auth)/register": {
      "filePath": "(auth)/register.lazy.tsx"
    },
    "/(profile)/notifications": {
      "filePath": "(profile)/notifications.lazy.tsx"
    },
    "/(profile)/profile": {
      "filePath": "(profile)/profile.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
