/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const StatsLazyImport = createFileRoute('/stats')()
const MoreLazyImport = createFileRoute('/more')()
const LoginLazyImport = createFileRoute('/login')()
const AssetsLazyImport = createFileRoute('/assets')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const StatsLazyRoute = StatsLazyImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/stats.lazy').then((d) => d.Route))

const MoreLazyRoute = MoreLazyImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/more.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const AssetsLazyRoute = AssetsLazyImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/assets.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreLazyImport
      parentRoute: typeof rootRoute
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/assets': typeof AssetsLazyRoute
  '/login': typeof LoginLazyRoute
  '/more': typeof MoreLazyRoute
  '/stats': typeof StatsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/assets': typeof AssetsLazyRoute
  '/login': typeof LoginLazyRoute
  '/more': typeof MoreLazyRoute
  '/stats': typeof StatsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/assets': typeof AssetsLazyRoute
  '/login': typeof LoginLazyRoute
  '/more': typeof MoreLazyRoute
  '/stats': typeof StatsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/assets' | '/login' | '/more' | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/assets' | '/login' | '/more' | '/stats'
  id: '__root__' | '/' | '/about' | '/assets' | '/login' | '/more' | '/stats'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  AssetsLazyRoute: typeof AssetsLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  MoreLazyRoute: typeof MoreLazyRoute
  StatsLazyRoute: typeof StatsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  AssetsLazyRoute: AssetsLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  MoreLazyRoute: MoreLazyRoute,
  StatsLazyRoute: StatsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/assets",
        "/login",
        "/more",
        "/stats"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/assets": {
      "filePath": "assets.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/more": {
      "filePath": "more.lazy.tsx"
    },
    "/stats": {
      "filePath": "stats.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
